pr:
  autoCancel: true

stages:
- stage: test
  jobs:
    - job: OSX
      timeoutInMinutes: 0
      pool:
        vmImage: 'macOS-latest'
      steps:
      - bash: |
          brew install micromamba
        displayName: Install micromamba
      - bash: |
          micromamba config --set always_yes yes --set changeps1 no
          micromamba info -a
          cat requirements_CI.txt | awk -v vp=3.7 'BEGIN{print "python =="vp}{print}' > requirements_CI_updated.txt
          micromamba create -n pygenometracks --yes -c conda-forge -c bioconda --file requirements_CI_updated.txt
          micromamba activate pygenometracks
          python -m pip install .
        displayName: installing dependencies
