pr:
  autoCancel: true

stages:
- stage: lint
  jobs:
    - job: Linux
      timeoutInMinutes: 0
      pool:
        vmImage: 'Ubuntu-latest'
      container: python:3.12
      steps:
      - bash: |
          echo "##vso[task.prependpath]$HOME/.local/bin"
          hash -r
        displayName: Add .local/bin to PATH
      - bash:
          python -m pip install --user --upgrade flake8
        displayName: install flake8
      - script:
          flake8 . --exclude=.venv,.build,build --ignore=E501,W503
        displayName: linting
- stage: test
  dependsOn: [lint]
  condition: succeeded()
  jobs:
    - job: Linux
      timeoutInMinutes: 0
      pool:
        vmImage: 'ubuntu-latest'
      strategy:
        matrix:
          Python310LowMatplotlib:
            python.version: '3.10'
            matplotlib.version: '3.8.4'
          # I cannot use 3.13 because pairix has no 3.13 on bioconda
          Python312HighMatplotlib:
            python.version: '3.12'
            matplotlib.version: '3.11.1'

      steps:
      - bash: |
          "${SHELL}" <(curl -L micro.mamba.pm/install.sh)
        displayName: Install micromamba
      - bash: |
          cat requirements_CI.txt | awk -v v=$(matplotlib.version) -v vp=$(python.version) 'BEGIN{print "python =="vp}{if($0~/matplotlib/){$0="matplotlib =="v}; print}' > requirements_CI_updated.txt
          micromamba create -n pygenometracks --yes -c conda-forge -c bioconda --file requirements_CI_updated.txt
          eval "$(micromamba shell hook --shell bash)"
          micromamba activate pygenometracks
          python -m pip install .
        displayName: installing dependencies
      - script: |
          eval "$(micromamba shell hook --shell bash)"
          micromamba activate pygenometracks
          py.test pygenometracks --doctest-modules -n 4
        displayName: pytest
    - job: OSX
      timeoutInMinutes: 0
      pool:
        vmImage: 'macOS-latest'
      strategy:
        matrix:
          Python310LowMatplotlib:
            python.version: '3.10'
            matplotlib.version: '3.8.4'
          Python312HighMatplotlib:
            python.version: '3.12'
            matplotlib.version: '3.11.1'

      steps:
      - bash: |
          brew install micromamba
        displayName: Install micromamba
      - bash: |
          eval "$(micromamba shell hook --shell bash)"
          cat requirements_CI.txt | awk -v v=$(matplotlib.version) -v vp=$(python.version) 'BEGIN{print "python =="vp}{if($0~/matplotlib/){$0="matplotlib =="v}; print}' > requirements_CI_updated.txt
          micromamba create -n pygenometracks --yes -c conda-forge -c bioconda --file requirements_CI_updated.txt
          eval "$(micromamba shell hook --shell bash)"
          micromamba activate pygenometracks
          echo $PATH
          python -m pip install .
        displayName: installing dependencies
      - script: |
          eval "$(micromamba shell hook --shell bash)"
          micromamba activate pygenometracks
          py.test pygenometracks --doctest-modules -n 4
        displayName: pytest

- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
  - stage: Deploy
    dependsOn: [test]
    condition: succeeded()
    jobs:
    - job: pypi
      pool:
        vmImage: 'Ubuntu-latest'
      container: python:3.8
      steps:
      - script: |
          python -m pip install --upgrade pip
          pip install build
          python -m build
          python -m pip install --user --upgrade twine
          python -m twine upload -r pypi dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: $(PGT_TOKEN)
        displayName: 'Push to Python Package Index'
