pr:
  autoCancel: true

stages:
- stage: test
  jobs:
    - job: OSX
      timeoutInMinutes: 0
      pool:
        vmImage: 'macOS-latest'
      strategy:
        matrix:
          Python38LowMatplotlib:
            python.version: '3.8'
            matplotlib.version: '3.1.1'
          Python38HighMatplotlib:
            python.version: '3.8'
            matplotlib.version: '3.5.1'
          Python39HighMatplotlib:
            python.version: '3.9'
            matplotlib.version: '3.5.1'
      steps:
      - bash: |
          brew install micromamba
        displayName: Install micromamba
      - bash: |
          eval "$(micromamba shell hook --shell bash)"
          cat requirements_CI.txt | awk -v v=$(matplotlib.version) -v vp=$(python.version) 'BEGIN{print "python =="vp}{if($0~/matplotlib/){$0="matplotlib =="v}; print}' > requirements_CI_updated.txt
          micromamba create -n pygenometracks --yes -c conda-forge -c bioconda --file requirements_CI_updated.txt
          micromamba activate pygenometracks
          echo $PATH
          python -m pip install .
        displayName: installing dependencies
      - script: |
          eval "$(micromamba shell hook --shell bash)"
          micromamba activate pygenometracks
          py.test pygenometracks --doctest-modules -n 4
        displayName: pytest
